### ISSUE TITLE
Topcode (maximum value) of ACS home values

### ISSUE THREAD

**Issue by jo-fleck** [jiaxitan/ASEC_ACS_match_julia#12]
As explained [here](https://usa.ipums.org/usa-action/variables/VALUEH#codes_section), the ACS variable VALUEH is topcoded at $ 1mio until 2007. From then, it has state specific topcodes. 

-> What's the fraction of topcoded observations? And how does it differ by state? (Can affect our matching outcomes.)

**Comment by jiaxitan** [comment]
Less than 1% of households in each state are top-coded. This is true for both 10/11 and 15/16 sample.
Even when using QVALUEH, only around 5% home values are altered.

-> We don’t have to worry about topcodes on the house values when we do the matching.
