### ISSUE TITLE
Update and improve geo matching

### ISSUE THREAD

**Issue by jo-fleck** [jiaxitan/ASEC_ACS_match_julia#7]
Implement the updated matching of non identified counties we discussed today (March 23)

**Comment by jiaxitan** [comment]
Just uploaded the updated matching

**Comment by jiaxitan** [comment]
The procedure of matching PUMA to county in ACS helps to identify 2 more counties that were not originally identified in ACS. 

However, there are a lot of ACS individuals living in the 2 counties. Before identifying the 2 extra counties, 42% of the individuals in our ACS sample have un-identified counties. This number was reduced to 34% after identifying the 2 extra counties.
